project:
  type: website
  output-dir: docs
  
website:
  title: "Jessica Applegate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - writings.qmd
      - designs.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



