project:
  type: website
  output-dir: docs
  
website:
  title: "Jessica Applegate"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - about.qmd
      - ResearchPortfolio.qmd
      - designs.qmd
      - writings.qmd
      - Resume.qmd
      - icon: linkedin 
        href: https://www.linkedin.com/in/jessica-applegate-197b6b230/
      
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true



